In [6]:
!pip install joblib

In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import numpy as np

In [16]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4 #small random weights
        training = (eta is not None) and (epochs is not None)
        if training:
            print(f"initial weights before training : \n{self.weights}")
        self.eta = eta
        self.epochs = epochs 
        
    def z_function(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
    
    def fit(self, x, y):
        self.x = x
        self.y = y
        x_with_bias = np.c_[self.x, -np.ones((len(self.x), 1))]
        print(f"x with bias :\n {x_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"For epoch >> {epoch}")
            print("--"*10)
            
            z = self.z_function(x_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error : \n{self.error}")
            
            self.weights = self.weights  + self.eta * np.dot(x_with_bias.T, self.error)
            print(f"updated weights after epoch : {epoch}/{self.epochs}: \n{self.weights}")
            print("##"*10)
            
        
    
    def predict(self, x):
        x_with_bias = np.c_[x, -np.ones((len(x), 1))]
        z = self.z_function(x_with_bias, self.weights)
        return self.activation_function(z)
        
    
    def total_loss(self):
        total_loss = np.sum(self.error)
        print(f"\n total loss : {total_loss}\n")
        return total_loss
    
    def create_directory(self,model_dir, filename):
        os.makedirs(model_dir, exist_ok=True)
        return os.path.join(model_dir, filename)


In [12]:
def prepare_data(df, target_col="y"):
    x = df.drop(target_col, axis=1)
    y = df[target_col]
    return x, y

In [13]:
AND = {
    "x1":[0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,0,0,1]
}
df = pd.DataFrame(AND)

In [17]:
x, y = prepare_data(df)
ETA = 0.1
EPOCHS = 10
model_and = Perceptron(eta=ETA, epochs = EPOCHS)
model_and.fit(x, y)

_ = model_and.total_loss()

initial weights before training : 
[-1.49234593e-05  1.53704304e-04 -1.85259482e-04]
x with bias :
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
For epoch >> 0
--------------------
predicted value after forward pass: 
[1 1 1 1]
error : 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch : 0/10: 
[-0.10001492 -0.0998463   0.29981474]
####################
--------------------
For epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch : 1/10: 
[-1.49234593e-05  1.53704304e-04  1.99814741e-01]
####################
--------------------
For epoch >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch : 2/10: 
[0.09998508 0.1001537  0.09981474]
####################
--------------------
For epoch >> 3
-----------------

In [18]:
OR = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "y": [0, 1, 1, 1]
}
df_or = pd.DataFrame(OR)
df_or

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [19]:
x, y = prepare_data(df_or)
ETA = 0.1
EPOCHS = 10
model_or = Perceptron(eta=0.1, epochs=10)
model_or.fit(x, y)
_ = model_or.total_loss()

initial weights before training : 
[1.52778902e-05 3.35967862e-05 8.93819941e-05]
x with bias :
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
For epoch >> 0
--------------------
predicted value after forward pass: 
[0 0 0 0]
error : 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch : 0/10: 
[ 0.20001528  0.2000336  -0.29991062]
####################
--------------------
For epoch >> 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch : 1/10: 
[ 0.20001528  0.2000336  -0.19991062]
####################
--------------------
For epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch : 2/10: 
[ 0.20001528  0.2000336  -0.09991062]
####################
--------------------
For epoch >> 3
--------------------
predicte